export const VIEW_SEARCH = 'VIEW_SEARCH';
export const VIEW_MOVIE  = 'VIEW_MOVIE';

export const ACTION_BEGIN_NAVIGATION   = Symbol('ACTION_BEGIN_NAVIGATION');
export const ACTION_NAVIGATE_TO_SEARCH = Symbol('ACTION_NAVIGATE_TO_SEARCH');
export const ACTION_NAVIGATE_TO_MOVIE  = Symbol('ACTION_NAVIGATE_TO_MOVIE');